### ISSUE TITLE
Error when running > runStsPlot

### ISSUE THREAD

**Issue by el42008** [PacificBiosciences/stsPlots#1]
Hi, I am trying the script in a single csv file). the plots seem to be generated and also the pdf files, but I can not open it. It says is corrupted
> runStsPlots(c("-folder","/home/el42208/PacBio_assembly/StsPlots/"))
[1] "prueba_p0.sts.csv"
[1] "prueba_p0.sts.csv"
[1] "plot 1 done"
[1] "plot 2 done"
[1] "plot 3 done"
[1] "plot 4 done"
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
[1] "plot 5 done"
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
[1] "plot 6 done"
[1] "plot 7 done"
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
[1] "plot 8 done"
Error: Unknown parameters: theme
 
I do not understand the error because ggplot2 should use theme now instead of opts so I do not know where the problem is.

Thank you in advance for your help

**Comment by rhallPB** [comment]
Can you confirm that you are using the validated versions of the required modules?
R version 3.0.3 (2014-03-06)
ggplot2_0.9.3.1
plyr_1.8.1
Hmisc_3.14-3       
Biostrings_2.30.1

Unfortunately this is an old script, that hasn't been widely tested across multiple versions.

**Comment by el42008** [comment]
Hi,

Thank you for answering so fast!

R version 3.2.3 (2015-12-10)" I am using because it is the one installed in
my cluster. then I installed I guess the last versions for plyr, ggplot2
and reshaped2 but I did not know I have to install Hmisc and  Biostrings

So, do you think this might be the problem??

Thank you and sorry ofr taking your time

Cheers



2016-03-16 16:57 GMT+00:00 rhallPB <notifications@github.com>:

**Comment by bowhan** [comment]
I think the problem is that option `theme` has been removed from `qplot` thus the error message "Error: Unknown parameters: theme".
Can you please edit the `stsPlots.R` file by deleting `theme="bw",` and adding `+theme_bw()` outside of the parenthesis? So the lines 161–164 looks like
```R
  p <- qplot(data=prod,x=BaseIpd, y=..count.., binwidth=0.02, geom='freqpoly') +
    labs(title="IPD Histogram : Oxygen Exclusion", x="Inter-pulse Duration", y="Counts") +
    geom_vline(xintercept=0.25,lwd=1,color=ifelse(ipdMean<0.25,'blue','red')) +
	theme_bw() +
```

**Comment by el42008** [comment]
Hi thanks,


Now the theme error is solved but instead it appears

Error: Unknown parameters: NA

sorry

2016-03-16 17:19 GMT+00:00 Bo Han <notifications@github.com>:

**Comment by bowhan** [comment]
When you delete `theme="bw",`, did you also delete the comma? The error is caused by two consecutive comma `, ,` thus an empty (NA) parameter.

**Comment by el42008** [comment]
Thank you!!

Now is working!

Now I will go throught the graph to see if I understand what I am getting

You made my day! Cheers

Ele

2016-03-16 17:30 GMT+00:00 Bo Han <notifications@github.com>:
